Forge stations
stanulet27/NeoForge pull request #12
Opened 2024-06-12 18:36 UTC by stanulet27

Set up scene to use new artwork.
Implement undo functionality for planning phase.
Create new shader for physics accurate blackbody radiation.
Set up camera views for different forging related stations (heating, cooling, planning, hitting)
Set up overview camera for forging station

2024-06-14 20:16 UTC, Chaseao requested changes
Bug: Text doesn't change for pull out of furnace
Steps: Click part, put in furnace, click second part

Bug: Part doesn't auto cool
Steps: Place in furnace, take part out

Bug: Place in furnace text doesn't update
Steps: Place in furnace, take part to planning -> hammering -> cooling, text does not match place in water until clicked. Same for the reverse situation

Bug: Part camera doesn't move with part correctly
Steps: Click long rectangular part, Go to planning, move part up and down vs left and right, different camera behavior

Bug: UI does not update with clicking the 1-5 station keys
Steps: Enter station -> Click a part -> send to planning -> press one of the 1-5 keys

Bug: Multiple parts can be sent to the planning phase at the same time
Steps: Click part, send to planning, press 2 to swap to heating, click new part, send to planning, repeat. Overall doesn't seem to know how to handle if use leaves a part midway through the process, should auto send to the heating station.

Future Feature Request: Ability to tell which part you've selected and to see it put into the furnace

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationController.cs
> +        FindObjectsOfType<Deformable>().ToList().ForEach(deformable => deformable.Clicked -= OnPartSelected );
extra space

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationController.cs
> +        if(_activePart == null) return;
missing space

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationController.cs
> +        if(_activePart == null) return;
Also rembember that null check is expensive and update is called often

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationController.cs
> +        //get new UI
redundent comments

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationController.cs
> +        {   if(_currentStation.Value == Station.Heating) _heatingCoolingButton.text = "Place in Furnace";
Ternary statment

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationController.cs
> +        else
else if, else to reduce nesting

2024-06-14 20:16 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/StationSwitcher.cs
> +    [SerializeField] private UnityEvent<Station> _changeStation;
Tooltips

2024-06-14 22:54 UTC, stanulet27 commented on Assets/NeoForge/Scripts/Input/ControllerManager.cs
> -
Merge error. My bad

2024-06-14 22:59 UTC, stanulet27 commented on Assets/_InDevelopment/Chris/RefactoredScripts/DeformationHandler.cs
> +        public void UndoLastDeformation()
This is handled by the server. Only the requests should be buffered and happen in order until there is nothing to undo. At this point it just keeps returning the start mesh

2024-06-14 23:06 UTC, stanulet27 commented on Assets/_InDevelopment/Chris/RefactoredScripts/ForgedPart.cs
> +            _outFurnacePosition = new GameObject("@OutFurnacePosition").transform;
This is create a game object, the reference is stored here and nothing else should ever access this. Its just a way to store the transform since you can't create them without gameobjects

2024-06-14 23:11 UTC, stanulet27 commented on Assets/_InDevelopment/Chris/RefactoredScripts/MeshSimilarityCalculator.cs
> +                if (child.parent == part.transform)
My bad brain rot got to me. I thought it would take all children not just immediate children

2024-06-14 23:14 UTC, stanulet27 commented on Assets/_InDevelopment/Chris/RefactoredScripts/SharedState.cs
> +
How is this supposed to be fixed?

2024-06-14 23:49 UTC, stanulet27 commented
> Bug: Text doesn't change for pull out of furnace Steps: Click part, put in furnace, click second part
> 
> Bug: Part doesn't auto cool Steps: Place in furnace, take part out
> 
> Bug: Place in furnace text doesn't update Steps: Place in furnace, take part to planning -> hammering -> cooling, text does not match place in water until clicked. Same for the reverse situation
> 
> Bug: Part camera doesn't move with part correctly Steps: Click long rectangular part, Go to planning, move part up and down vs left and right, different camera behavior
> 
> Bug: UI does not update with clicking the 1-5 station keys Steps: Enter station -> Click a part -> send to planning -> press one of the 1-5 keys
> 
> Bug: Multiple parts can be sent to the planning phase at the same time Steps: Click part, send to planning, press 2 to swap to heating, click new part, send to planning, repeat. Overall doesn't seem to know how to handle if use leaves a part midway through the process, should auto send to the heating station.
> 
> Future Feature Request: Ability to tell which part you've selected and to see it put into the furnace

Just a couple notes on the bugs. 

Bug 1 has been fixed.

Bug 2 is not a bug auto cooling just isn't implemented yet. We need to decide on where the part can cool and how time should pass.

Bug 3 has been fixed.

Bug 4 will never be encountered in-game. The reason this occurs is because to make these "new parts" i scaled the gameobject by 2 in different directions. This changed the speed at which they move in these second directions.

Bug 5 is not a bug. I didn't change the UI so the player would be forced to either return the part or complete what they were doing. It was basically just trying to make it so bug 6 is not encountered. 

Bug 6; see bug 5

2024-06-15 10:18 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/ForgedPart.cs
> +            _outFurnacePosition = new GameObject("@OutFurnacePosition").transform;
...I'm stupid ignore me

2024-06-15 10:21 UTC, Chaseao commented on Assets/_InDevelopment/Chris/RefactoredScripts/SharedState.cs
> +
![image](https://github.com/stanulet27/NeoForge/assets/91914376/d2d9055e-42da-4006-895b-58036e44246a)
Listen this is what its showing me xD

2024-06-15 10:27 UTC, Chaseao requested changes
Bug: Okay then I'll make the amendment that the bug is that the part does not return to the heating station upon pressing move it back
Steps: Select a part, send to planning, return to heating station, click another part, click yes, no part was returned

2024-06-15 13:13 UTC, stanulet27 commented on Assets/NeoForge/Scripts/Input/ControllerManager.cs
> -
Yes its been back

2024-06-15 13:15 UTC, stanulet27 commented on Assets/_InDevelopment/Chris/RefactoredScripts/SharedState.cs
> +
I know but I'm not seeing that the issue is. Both get and set need to be explicitly defined. I modeled this based on the other shared data you've  made

2024-06-15 13:36 UTC, stanulet27 commented
> Bug: Okay then I'll make the amendment that the bug is that the part does not return to the heating station upon pressing move it back Steps: Select a part, send to planning, return to heating station, click another part, click yes, no part was returned

Bug has been fixed. I made it so that a a part cant be selected until the part that was already selected is returned. It a little but not obvious to the user this is how it works so I'll add a pop up later along with the animation to show which part is selected.

2024-06-17 13:11 UTC, Chaseao approved these changes

2024-06-17 13:11 UTC, merged